addSbtPlugin("org.scoverage"  % "sbt-scoverage"      % "1.9.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.4.4")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"     % "1.5.10")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.13.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"       % "0.9.33")
