addSbtPlugin("org.scoverage"  % "sbt-scoverage"      % "1.8.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"       % "2.4.2")
addSbtPlugin("com.geirsson"   % "sbt-ci-release"     % "1.5.7")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.10.1")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"       % "0.9.27")
